version: "3.1"
services:
  server:
    image: virtool/virtool:5.5.5
    depends_on:
      - mongo
      - redis
      - postgres
    command: >
      --data-path="/data"
      --db-connection-string="mongodb://mongo:27017"
      --postgres-connection-string="postgresql+asyncpg://virtool:virtool@postgres/virtool"
      --redis-connection-string="redis://redis:6379"
      server
      --host=0.0.0.0
      --port=9950
    ports:
      - "9950:9950"
    volumes: 
      - vt_data:/data

  jobs-api:
    image: virtool/virtool:5.5.5
    depends_on:
      - mongo
      - redis
      - postgres
    command: >
      --data-path="/data"
      --db-connection-string="mongodb://mongo:27017"
      --postgres-connection-string="postgresql+asyncpg://virtool:virtool@postgres/virtool"
      --redis-connection-string="redis://redis:6379"
      jobsAPI
      --host=0.0.0.0
      --port=9990
    ports:
      - "9990:9990"
    volumes:
      - vt_data:/data

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - vt_mongo_data:/data/db
    logging:
      driver: none

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - vt_redis_data:/data
    logging:
      driver: none

  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: virtool
      POSTGRES_PASSWORD: virtool
    volumes:
      - vt_postgres_data:/var/lib/postgresql/data
    logging:
      driver: none

  pathoscope:
    image: virtool/pathoscope:debug
    restart: always
    entrypoint: workflow
    command: >
      run-from-redis
      --redis-url="redis://redis:6379"
      --jobs-api-url="http://jobs-api:9990/api"
      --dev-mode
      --is-analysis-workflow
      jobs_pathoscope_bowtie

  create-sample:
    image: virtool/create-sample:2.0.1
    restart: always
    entrypoint: workflow
    command: >
      run-from-redis
      --redis-url="redis://redis:6379"
      --jobs-api-url="http://jobs-api:9990/api"
      --dev-mode
      --is-analysis-workflow
      jobs_create_sample

  create-subtraction:
    image: virtool/create-subtraction:2.0.1
    restart: always
    entrypoint: workflow
    command: >
      run-from-redis
      --redis-url="redis://redis:6379"
      --jobs-api-url="http://jobs-api:9990/api"
      --dev-mode
      --is-analysis-workflow
      jobs_create_subtraction

  build-index:
    image: virtool/build-index:2.0.1
    restart: always
    entrypoint: workflow
    command: >
      run-from-redis
      --redis-url="redis://redis:6379"
      --jobs-api-url="http://jobs-api:9990/api"
      --dev-mode
      --is-analysis-workflow
      jobs_build_index
      

volumes:
  vt_data:
  vt_mongo_data:
  vt_redis_data:
  vt_postgres_data:
