name: ci

on:
  pull_request:
    branches:
      - "debug"
  push:
    branches:
      - "debug"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
  test:
    runs-on: ubuntu-20.04
    container:
      image: virtool/workflow:1.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Run Tests
        run: |
          poetry install
          poetry run pytest

  dockerhub:
    name: dockerhub
    runs-on: ubuntu-20.04
    needs: 
        - test
        - commitlint
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: virtool/pathoscope:debug
