name: publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  dockerhub:
    name: dockerhub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: virtool/pathoscope:${{ github.event.release.tag_name }}
          target: "base"
  ghcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    if: github.repository_owner == 'Virtool'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write VERSION file
        run: echo ${{ github.event.release.tag_name }} > VERSION
      - name: Update pyproject.toml version
        run: sed -i 's/0\.0\.0/${{ github.event.release.tag_name }}/' pyproject.toml
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/virtool/pathoscope
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: "base"
          labels: ${{ steps.meta.outputs.labels }}
